### PR TITLE
Fix call extra methods

### PR DESCRIPTION
**Pull request by Drummer01**
This PR fixes inability to call extra methods with passing an argument as described [here](http://docs.apiato.io/miscellaneous/magical-call/)

### CODE REVIEW

**Comment by johannesschobel** [comment]
This is a breaking change, right?
My application does not work any more - because of this PR?! Has the syntax of passing variables to the magic call been changed?! @Drummer01 @Mahmoudz

**Comment by johannesschobel** [comment]
Till now i was calling
```php
$teams = $this->call(GetAllTeamsTask::class, [], ['ordered', ['filterByUser' => [$user]]]);
```
to get all "my" Teams (e.g., the teams the current user is participating)..
However, after running `composer update`, the `filterByUser` method is not called any more!

This must be a bug @Mahmoudz

**Comment by johannesschobel** [comment]
If I manually revert this commit everything works fine and as expected.
Furthermore, the way i used to call additional methods with params is compliant to the docs, or am i missing something?!

**Comment by Mahmoudz** [comment]
@johannesschobel thanks for noticing that. I've fixed the releases now. Kindly run composer update and let us know if everything is working fine now. Best,

**Comment by johannesschobel** [comment]
woooooooooooooooha, it works again @Mahmoudz & @Drummer01 
Thanks a lot ;)

**Pull request merged**
