### PR TITLE
fix hashedKey()

### PR DESCRIPTION
**Pull request by johannesschobel**
Fixes the `getHashedKey()` method as described in https://github.com/apiato/apiato/issues/317 .

The **new** behavior (and that should be the intended one) is as follows:
```php
$entity->getHashedKey(); // => AS BEFORE: Uses keyName (default to 'id') to calculate the hashed value!
$entity->getHashedKey(null); // => AS BEFORE: same as above
$entity->getHashedKey('id'); // uses $entity->id to calculate the hashed value
$entity->getHashedKey('customID'); // uses $entity->customID to calculate the value
$entity->getHashedKey('adfadfq'); // returns "" if the field cannot be found in this model
```

This PR should not break anything, because of the following reasons:
1) If you just used the `->getHashedKey()` method in your Transformers before, the method was called without parameter. This behavior is still the same!
2) The method was already broken before 😄

### CODE REVIEW

**Comment by johannesschobel** [comment]
Hey @yalsicor : Can you please take a look at my changes here?
i think, this would be better readable? What do you think?

**Comment by johannesschobel** [comment]
i also tend to return `null` (instead of `"" (empty string)` if trying to encode a "unknown" value.. what do you think @yalsicor

**Comment by yalsicor** [comment]
@johannesschobel looks good to me.
if we return `null` if the `$field` does not exist, there would not be a distinction between `$field = null` and `$field` not existing, wouldn't it? Maybe we can trhow a warning to the logs then? Otherwise it would be hard to debug, i think.

Yal

**Comment by johannesschobel** [comment]
@yalsicor If you pass `null` to the method, the `key` (most likely `id`) is used to request the data. However, i would like to `return null` if the `$field` does not exist in `$model->attributes`.

Currently (in my and your approach), `->getHashedKey('foobar')` returns `""`, if the field `foobar` does not exist in `$model`... Actually, i don't know, it that is a problem, however.. `""` is still fine..

**Comment by yalsicor** [comment]
@johannesschobel Yes, that is what I meant. If the **value** is null, `null` is returned. If the `$field` is not existing, its good to have `""` returned for debug purposes, I think.

**Comment by johannesschobel** [comment]
actually, if the `value` is null, `""` is returned.. (in your PR as well).

**Comment by yalsicor** [comment]
Mh, I thought I tested that. I think it should return `null` when the value is `null`.

**Comment by johannesschobel** [comment]
actually... i don't think that would be a good idea.. because the HashID Encoder just takes `numeric` values into account for generating such IDs.. `String`-values and so on are also converted to `""`.. So basically, the current approach would be a consistent behavior

**Comment by yalsicor** [comment]
But isn't that what the original poster in apiato/apiato#317 asked for? to get `null` if the value is `null`?

**Comment by johannesschobel** [comment]
i think, we should have one style, how all (!) _invalid_ hash-ids are represented. In this case, i would definately vote for the approach, that the `HashId` library, apiato relies on, uses.. The library outputs "invalid" values that should be converted to a hashid as `""`.

**Comment by yalsicor** [comment]
Makes sense to me. Thanks for diving into this.

**Pull request merged**
