### PR TITLE
fix: controller generator

### PR DESCRIPTION
**Pull request by innoflash**
## Description
[//]: # (Please include a summary of the change and which issue is fixed.  )
[//]: # (Please also include relevant motivation and context.  )
[//]: # (List any dependencies that are required for this change.)
This PR aims to solve the issue I mentioned on #193 
The controller generator seems to be misbehaving and we eventually have a need to go fix the generated code.

Short version is controllers are built with the wrong model.
## Type of change
[//]: # (Please put an x in the box that apply.)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (refactoring a current feature, method, etc...)
- [ ] Code Coverage (adding/removing/updating/refactoring tests)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Remove feature (non-breaking change which removes functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

I simply added a `model` option to the inputs.
Updated command is:
`php artisan apiato:generate:controller --container Locations --model District`
The model can also be requested for if one isnt provided in the command
Screenshot 2024-01-19 at 20 11 02

The generated file has this code:
```php
<?php

namespace App\Containers\AppSection\Locations\UI\API\Controllers;

use Apiato\Core\Exceptions\IncorrectIdException;
use Apiato\Core\Exceptions\InvalidTransformerException;
use App\Containers\AppSection\Locations\Actions\CreateDistrictAction;
use App\Containers\AppSection\Locations\UI\API\Requests\CreateDistrictRequest;
use App\Containers\AppSection\Locations\UI\API\Transformers\DistrictTransformer;
use App\Ship\Exceptions\CreateResourceFailedException;
use App\Ship\Parents\Controllers\ApiController;
use Illuminate\Http\JsonResponse;

class TestFixController extends ApiController
{
    public function __construct(
        private readonly CreateDistrictAction $action,
    ) {
    }

    public function __invoke(CreateDistrictRequest $request): JsonResponse
    {
        $district = $this->action->run($request);

        return $this->created($this->transform($district, DistrictTransformer::class));
    }
}
```

This now makes use of the desired model in this container

### CODE REVIEW

**Comment by innoflash** [comment]
Works for plural modelling too:

```php
public function __construct(
        private readonly ListDistrictsAction $action
    ) {
    }

    public function __invoke(ListDistrictsRequest $request): array
    {
        $districts = $this->action->run($request);

        return $this->transform($districts, DistrictTransformer::class);
    }
```

**Comment by Mohammad-Alavi** [comment]
@innoflash Thank you for this! 💪
Ill review it in the comming days. Sorry for the delay 😭

**Comment by innoflash** [comment]
> @innoflash Thank you for this! 💪 Ill review it in the comming days. Sorry for the delay 😭

Sure, take your time.

I may have found a couple more things I think I can help solve on the framework.
Otherwise Apiato is a marvel to work with @Mohammad-Alavi

**Comment by innoflash** [comment]
@Mohammad-Alavi where is the test file for the controller generation so I can add a test for this addition?

**Review by Mohammad-Alavi — APPROVED** [review]

**Pull request merged**
