### PR TITLE
"Cannot declare class" errors in PHPUnit

### PR DESCRIPTION
**Pull request by fosron**
A simple change just in case we have Factories loaded already.

### CODE REVIEW

**Comment by johannesschobel** [comment]
never ran into this problem.. can you explain the problem? just curious

**Comment by fosron** [comment]
For some reason, while running PHPUnit tests, this file (Loaders/FactoryMixer/FactoriesLoader.php) tries to load the Factories inside Containers for second time. Which is not needed because they are being loaded by Comspoer autoload.

**Comment by fosron** [comment]
This *should* not break anything. Just in case it tries to load something for a second time, it will not fail with a fatal error.

**Comment by johannesschobel** [comment]
Changing from `include(...)` to `require_once` fails every test-case in on my local machine (latest apiato version!)

**Comment by johannesschobel** [comment]
Hey there.. i am using `apiato/core : dev-master` which is basically nearly the same as `2.4.5`...
you can try changing the respective line in your local `core` (in your project) and run `phpunit`. 

For me, every test fails..

I have just downloaded a new version of apiato, no adaptations whatsoever..

**Comment by fosron** [comment]
@johannesschobel So the problem is that our current implementation of factories is Object-Based vs original Apiato where it's a defined callback (https://github.com/apiato/apiato/blob/master/app/Containers/User/Data/Factories/UserFactory.php). We need to either move them out of the Apiato Factory directory or to patch up this file to not double-load the files.

**Comment by johannesschobel** [comment]
thanks for the feedback on this.. glad you figured it out!

**Pull request closed without merging**
