### PR TITLE
Let Requests access property use arrays as well

### PR DESCRIPTION
**Pull request by Kyslik**
Lets user (of Apiato) use arrays when setting up request's access property:

```php
protected $access = [
    'permissions' => ['manage-users', 'create-users'],
    'roles'       => ['user-manager', 'something-else'],
];
```

as well as piped string

```php
protected $access = [
    'permissions' => 'manage-users|create-users',
    'roles'       => 'user-manager|something-else',
];
```

### CODE REVIEW

**Comment by johannesschobel** [comment]
Hey there.. doesn't that break existing applications if we switch from `a|b` to `['a', 'b']`?

**Comment by johannesschobel** [comment]
Oh.. this just comes to my mind.. In the `check` function in this class uses `[]` and `|` in order to determine the syntactical order.. For example you can use `[]` to `AND` those constraints, and `|` to OR them...

**Comment by Kyslik** [comment]
@johannesschobel this PR touches only `$access`, this should not be BC, because pipe usage is not removed. PR just adds possibility to define roles/permissions as array instead of piped string.

`check()` function is not touched and irrelevant in this case

**Comment by johannesschobel** [comment]
I can see why one would like to use the `[]` notation.. however, i think we need to get an additional info from @Mahmoudz what he thinks about it.. 

I would allow for both styles (i.e., i would accept the PR).

@Kyslik : can you "inline" the second line of your commands? (the `else` part)?

**Comment by Mahmoudz** [comment]
Seems very convenient, since it supports both types without breaking anything. Thanks for the PR.

**Comment by johannesschobel** [comment]
i just added a small block to the docs: http://docs.apiato.io/components/requests/#access .. cheers

**Pull request merged**
