### PR TITLE
#100 override event service provider fix

### PR DESCRIPTION
**Pull request by denis019**

### CODE REVIEW

**Comment by deviouspk** [comment]
What's the purpose of this fix?

**Comment by denis019** [comment]
I have encounter the error where the model events is not triggered because the
\Illuminate\Database\Eloquent\Model::$dispatcher is having

**Comment by johannesschobel** [comment]
@deviouspk 
please read this ( https://github.com/apiato/apiato/issues/428 ) and this ( https://github.com/apiato/core/issues/100 ) issue here..

Do you see any problem with the fix?

**Comment by deviouspk** [comment]
I'm the one who wrote the custom event service provider that's why i asked. The behavior you are describing in that issue is really weird. The only thing the custom event service provider does is implement the shouldHandle feature (http://docs.apiato.io/components/events/#Queueing) on events. And since it overrides the default laravel event service provider it shouldn't bug when firing events from calling modelfactories in unit tests. Can you explain what you think is happening @denis019 ?

**Comment by denis019** [comment]
@deviouspk I have debug a lot to trace this weird behavior and came to the conclusion as a described in #100

**Comment by johannesschobel** [comment]
Hi @deviouspk and @denis019 
I haven't had time to look deeply into the code.. But from the looks you are still using @deviouspk 's EventServiceProvider but just load it **after** the "original" Laravel EventServiceProvider is loaded, right?

**Comment by denis019** [comment]
@johannesschobel you are correct, if we are overriding the 'original' laravel EventServiceProvider with our EventServiceProvider we should be insured that we are using it everywhere also in the Laravel DabaseServiceProvider.

The service provider initialization is the following:

\Illuminate\Events\EventServiceProvider::register
\Apiato\Core\Providers\ApiatoProvider::register
\Illuminate\Database\DatabaseServiceProvider::boot
       $this->app['events'] will return \Illuminate\Events\Dispatcher 
\Apiato\Core\Providers\ApiatoProvider::boot
\Apiato\Core\Abstracts\Events\Providers\EventServiceProvider::register

With the fix the initialization will be the following:
\Illuminate\Events\EventServiceProvider::register
\Apiato\Core\Providers\ApiatoProvider::register
\Apiato\Core\Abstracts\Events\Providers\EventServiceProvider::register
\Illuminate\Database\DatabaseServiceProvider::boot 
        $this->app['events'] will return \Apiato\Core\Abstracts\Events\Dispatcher\Dispatcher 
\Apiato\Core\Providers\ApiatoProvider::boot

**Comment by johannesschobel** [comment]
Do you agree @deviouspk ? I think this is ok and sounds good!

**Comment by deviouspk** [comment]
Yes ofcourse that's a bug we need to fix indeed. So if i understand your issue correctly the events were being fired but with the default laravel event service provider not the apiato one? So you were trying to use the shouldHandle feature but it didn't work. Is that correct?

**Comment by denis019** [comment]
@deviouspk I have encounter this issue running phpunit tests and using model factory in them, on models I have attached events on saving/saved as I described in apiato/apiato#428 I will need some more time to check other scenarios, but maybe we can expects some issue also in other use cases.

**Comment by deviouspk** [comment]
Ofcourse i understand that this causes issue if you use the apiato shouldhandle feature but. I don't really understand why events are not getting fired in your case. the default laravel event service provider should handle those events?

**Comment by denis019** [comment]
@deviouspk I will try to go over it again, and will come back to you with some more details.

**Comment by johannesschobel** [comment]
In this case I wait with merging :D

**Comment by deviouspk** [comment]
Better to wait. If what he's saying is correct there might be an underlying problem

**Comment by denis019** [comment]
@deviouspk good question was why Laravel event service provider didn't take care of Model events?
That is because on
```
public function boot()
    {
        Model::setConnectionResolver($this->app['db']);

        Model::setEventDispatcher($this->app['events']);
    }
```
`$this->app['events'] = \Illuminate\Events\Dispatcher`

After that in \Illuminate\Foundation\Testing\TestCase
```
protected function setUp()
    {
        if (! $this->app) {
            $this->refreshApplication();
        }

        $this->setUpTraits();

        foreach ($this->afterApplicationCreatedCallbacks as $callback) {
            call_user_func($callback);
        }

        Facade::clearResolvedInstances();

        // here we will override  \Illuminate\Events\Dispatcher with  
        // \Apiato\Core\Abstracts\Events\Dispatcher\Dispatcher
        // so  \Apiato\Core\Abstracts\Events\Dispatcher\Dispatcher dosent know about model events
        Model::setEventDispatcher($this->app['events']);

        $this->setUpHasRun = true;
    }
```
`$this->app['events']` is singleton and should be consistent through application

**Comment by johannesschobel** [comment]
Hey there,...
2 more thoughts on this:
1) Could it be that the `AP_ENV = testing` (that is used for the phpunit tests) may change such behaviour!?
2) Apiato creates a new "layer" above the `Illuminate/Testing` stuff, so maybe the error could be located there?

**Comment by deviouspk** [comment]
Hmm i don't fully understand why the custom apiato dispatcher wouldn't know how to handle model events. the custom dispatcher extends from \Illuminate\Events\Dispatcher. Or am i missing something?

**Comment by denis019** [comment]
\Illuminate\Database\Eloquent\Model
use \Illuminate\Database\Eloquent\Concerns\HasEvents Trait

\Illuminate\Database\Eloquent\Concerns\HasEvents::registerModelEvent
```
protected static function registerModelEvent($event, $callback)
    {
        if (isset(static::$dispatcher)) {
            $name = static::class;
           
           // here default laravel dispatcher will listen for model events
          // because the DatabaseServiceProvider has setup laravel default dispatcher
            static::$dispatcher->listen("eloquent.{$event}: {$name}", $callback);
        }
    }
```
- next we will set apiato dispatcher because here he is already register, this will replace laravel default dispatcher which has knowledge about model events
\Illuminate\Foundation\Testing\TestCase::setUp
```
protected function setUp()
    {
        if (! $this->app) {
            $this->refreshApplication();
        }

        $this->setUpTraits();

        foreach ($this->afterApplicationCreatedCallbacks as $callback) {
            call_user_func($callback);
        }

        Facade::clearResolvedInstances();

        Model::setEventDispatcher($this->app['events']);

        $this->setUpHasRun = true;
    }
```
please check \Illuminate\Database\Eloquent\Concerns\HasEvents::fireModelEvent
```
protected function fireModelEvent($event, $halt = true)
    {

        // here we will have apiato dispatcher which dosen't knows about model events
        if (! isset(static::$dispatcher)) {
            return true;
        }

        // First, we will get the proper method to call on the event dispatcher, and then we
        // will attempt to fire a custom, object based event for the given event. If that
        // returns a result we can return that result, or we'll call the string events.
        $method = $halt ? 'until' : 'fire';

        $result = $this->filterModelEventResults(
            $this->fireCustomModelEvent($event, $method)
        );

        if ($result === false) {
            return false;
        }

        return ! empty($result) ? $result : static::$dispatcher->{$method}(
            "eloquent.{$event}: ".static::class, $this
        );
    }
```

**Comment by denis019** [comment]
@deviouspk @johannesschobel I have tested without unit test Model events and they are working fine.

\App\Containers\Welcome\UI\API\Controllers\Controller::apiRoot
```
public function apiRoot()
    {
        $faker = Factory::create();
        $user = new User([
            'name' => $faker->name,
            'email' => $faker->unique()->safeEmail,
            'password' => Hash::make('testing-password'),
            'remember_token' => str_random(10),
            'is_client' => false,
        ]);

        $user->save();

        $message = Apiato::call('Welcome@FindMessageForApiRootVisitorAction');

        return response()->json($message);
    }
```
Model events will be handled by default laravel dispatcher because DatabaseServiceProvider set default one 
Model::setEventDispatcher($this->app['events']);
$this->app['events'] returns default dispatcher.

If I set model dispatcher (as Laravel Unit test does)
```
public function apiRoot()
    {
        Model::setEventDispatcher(App::make('events'));
        $faker = Factory::create();
        $user = new User([
            'name' => $faker->name,
            'email' => $faker->unique()->safeEmail,
            'password' => Hash::make('testing-password'),
            'remember_token' => str_random(10),
            'is_client' => false,
        ]);

        $user->save();

        $message = Apiato::call('Welcome@FindMessageForApiRootVisitorAction');

        return response()->json($message);
    }
```
The model events will not be fired.
App::make('events') should always return the same instance since is singleton.
In DatabaseServiceProvider we have one instance but in the rest of application we have another.

**Comment by johannesschobel** [comment]
wow, great analysis @denis019 ...
How do you think, we can properly solve it? Is the PR (i.e., overriding the default event service provider) still accurate or do we need to fix it the other way? What do you think?

**Comment by deviouspk** [comment]
Hey dennis i understand there are 2 different instances of the dispatcher one in database and one in the rest of the application. Caused by a bug that boots the databaseserviceprovider before we boot the custom apiato event service provider. We clearly need to fix that. But i still do not understand why the model events are not getting fired. Why does having 2 instances of the dispatcher affect this, it does not make any sense. Why does it matter wich dispatcher is firing the events?

**Comment by denis019** [comment]
@deviouspk model events are getting fired but in this case only laravelDefault dispatcher is listening on those events:
\Illuminate\Database\Eloquent\Concerns\HasEvents::registerModelEvent
```
protected static function registerModelEvent($event, $callback)
    {
        if (isset(static::$dispatcher)) {
            $name = static::class;
           
           // here default laravel dispatcher will listen for model events
          // because the DatabaseServiceProvider has setup laravel default dispatcher
            static::$dispatcher->listen("eloquent.{$event}: {$name}", $callback);
        }
    }
```
and laravel overiddes it with apiato dispatcher in unittests
\Illuminate\Foundation\Testing\TestCase

```
protected function setUp()
    {
        if (! $this->app) {
            $this->refreshApplication();
        }

        $this->setUpTraits();

        foreach ($this->afterApplicationCreatedCallbacks as $callback) {
            call_user_func($callback);
        }

        Facade::clearResolvedInstances();

        // here we will override  \Illuminate\Events\Dispatcher with  
        // \Apiato\Core\Abstracts\Events\Dispatcher\Dispatcher
        // so in \Illuminate\Database\Eloquent\Concerns\HasEvents::fireModelEvent we have
        // static::$dispatcher = \Apiato\Core\Abstracts\Events\Dispatcher\Dispatcher which dosent know about model events
        Model::setEventDispatcher($this->app['events']);

        $this->setUpHasRun = true;
    }
```

**Comment by deviouspk** [comment]
oh shit! i missed that i'm sorry. Ok perfect! So your fix registers the custom event service provider before the databaseserviceprovider is booted?

**Comment by johannesschobel** [comment]
as far as i have understood, it `overrides` it! I don't think, you can register **before** Laravel registers their providers!?

**Comment by denis019** [comment]
@deviouspk you are correct, because the register will happen first on All providers, and after that the booting of the providers will happen.
With this fix I just moved the Apiato EventServiceProvider to be registered in the ApiatoProvider Register method. So it would be available in each boot method if some service provider depends on it.

**Comment by denis019** [comment]
@johannesschobel you are correct, it overrides it, because the base service providers are registered here:
\Illuminate\Foundation\Application::registerBaseServiceProviders
```
protected function registerBaseServiceProviders()
    {
        $this->register(new EventServiceProvider($this));

        $this->register(new LogServiceProvider($this));

        $this->register(new RoutingServiceProvider($this));
    }
```

**Comment by johannesschobel** [comment]
ok.. this seems good to me.. i will merge the PR tomorrow morning if you are happy with this, as i am currently on the move!

just "thumb up" on this message @denis019 and @deviouspk in order to approve ;)

**Comment by johannesschobel** [comment]
thank you very much.. i just merged it to `core:master` but will provide a dedicated `core:2.4` release soon..

**Pull request merged**
